export const LOAD_EVENTS_START = "LOAD_EVENTS_START"
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS"
export const LOAD_EVENTS_ERROR = "LOAD_EVENTS_ERROR"

export const CREATE_EVENT_START = "CREATE_EVENT_START"
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS"
export const CREATE_EVENT_ERROR = "CREATE_EVENT_ERROR"

export const DELETE_EVENT_START = "DELETE_EVENT_START"
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS"
export const DELETE_EVENT_ERROR = "DELETE_EVENT_ERROR"

export const UPDATE_EVENT_START = "UPDATE_EVENT_START"
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS"
export const UPDATE_EVENT_ERROR = "UPDATE_EVENT_ERROR"

export const SEARCH_EVENT_START = "SEARCH_EVENT_START"
export const SEARCH_EVENT_SUCCESS = "SEARCH_EVENT_SUCCESS"
export const SEARCH_EVENT_ERROR = "SEARCH_EVENT_ERROR"